### ISSUE TITLE
Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference

### ISSUE THREAD

**Issue by khynantoque** [NordicSemiconductor/Android-Scanner-Compat-Library#131]
I'm getting this error and it crashes my application. Sometimes it will not occur, and I don't know why.
Here is my logcat:
```logcat

2022-11-13 16:29:02.787 31726-31726 AndroidRuntime          pid-31726                            E  FATAL EXCEPTION: main
                                                                                                    Process: com.khynsoft.EyeNav, PID: 31726
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
                                                                                                    	at com.khynsoft.ble.PluginActivity$1.onScanResult(PluginActivity.java:58)
                                                                                                    	at com.khynsoft.ble.nrf.BluetoothLeScannerCompat$ScanCallbackWrapper.handleScanResult(BluetoothLeScannerCompat.java:490)
                                                                                                    	at com.khynsoft.ble.nrf.BluetoothLeScannerImplLollipop$ScanCallbackWrapperLollipop$1$1.run(BluetoothLeScannerImplLollipop.java:263)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:900)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8668)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```

I did clone the project and change all the package to my package directory so it's different.

And here is the code:
```java
package com.khynsoft.ble;

import android.Manifest;
import android.content.pm.PackageManager;
import android.os.Build;
import android.os.Bundle;
import android.widget.Toast;

import androidx.annotation.NonNull;

import com.khynsoft.ble.nrf.BluetoothLeScannerCompat;
import com.khynsoft.ble.nrf.ScanCallback;
import com.khynsoft.ble.nrf.ScanResult;
import com.khynsoft.ble.nrf.ScanSettings;

public class PluginActivity extends UnityPlayerActivity {

    private BluetoothLeScannerCompat scanner;
    private static int rssi1 = 0;
    private static int rssi2 = 0;
    private static int rssi3 = 0;
    private static int rssi4 = 0;

    ScanCallback scanCallback = new ScanCallback() {
        @Override
        public void onScanResult(int callbackType, @NonNull ScanResult result) {
            switch (result.getDevice().getName()) {
                case "KunwareBLE1":
                    rssi1 = result.getRssi();
                    break;
                case "KunwareBLE2":
                    rssi2 = result.getRssi();
                    break;
                case "KunwareBLE3":
                    rssi3 = result.getRssi();
                    break;
                case "KunwareBLE4":
                    rssi4 = result.getRssi();
                    break;
            }
        }

        @Override
        public void onScanFailed(int errorCode) {
            super.onScanFailed(errorCode);
            Toast.makeText(PluginActivity.this, "Scan failed!", Toast.LENGTH_SHORT).show();
        }
    };

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Toast.makeText(this, "by Khyn Antoque", Toast.LENGTH_SHORT).show();
        scanner = BluetoothLeScannerCompat.getScanner();

        ScanSettings settings = new ScanSettings.Builder()
                .setLegacy(false)
                .setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY)
                .setMatchMode(ScanSettings.MATCH_MODE_AGGRESSIVE)
                .setNumOfMatches(ScanSettings.MATCH_NUM_MAX_ADVERTISEMENT)
                .build();


        Toast.makeText(this, "Scanning...", Toast.LENGTH_SHORT).show();

        String locationPermission = Build.VERSION.SDK_INT >= 29 ? Manifest.permission.ACCESS_FINE_LOCATION : Manifest.permission.ACCESS_COARSE_LOCATION;

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            this.requestPermissions(
                    new String[]{
                            locationPermission,
                            Manifest.permission.BLUETOOTH_ADMIN
                    }, 0);
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            this.requestPermissions(
                    new String[]{
                            Manifest.permission.BLUETOOTH_SCAN
                    }, 0);
        }

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            if (PluginActivity.this.checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT) != PackageManager.PERMISSION_GRANTED) {
                PluginActivity.this.requestPermissions(new String[]{
                        Manifest.permission.BLUETOOTH_CONNECT
                }, 0);
            }
        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            PluginActivity.this.requestPermissions(new String[]{
                    Manifest.permission.BLUETOOTH
            }, 0);
        }

        try {
            scanner.startScan(null, settings, scanCallback);
        } catch (Exception e) {
            Toast.makeText(this, "Error: " + e.getMessage(), Toast.LENGTH_SHORT).show();
        }
    }

    public int getRssi1() {
        return rssi1;
    }

    public int getRssi2() {
        return rssi2;
    }

    public int getRssi3() {
        return rssi3;
    }

    public int getRssi4() {
        return rssi4;
    }


    @Override
    protected void onDestroy() {
        super.onDestroy();
        scanner.stopScan(scanCallback);
    }
}

```

**Comment by khynantoque** [comment]
I fixed it, I just added a filter, and it works fine, I hope...
```java
List<ScanFilter> filters = new ArrayList<>();
        filters.add(new ScanFilter.Builder().build());
...
scanner.startScan(filters, settings, scanCallback);
```
