### ISSUE TITLE
An error occurred when quickly switching Bluetooth on and off and stopping scanning status.

### ISSUE THREAD

**Issue by Fly-Felix** [NordicSemiconductor/Android-Scanner-Compat-Library#145]
```
java.lang.IllegalStateException: BT Adapter is not turned ON
   at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
   at android.bluetooth.le.BluetoothLeScanner.stopScan(BluetoothLeScanner.java:266)
   at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerImplLollipop.stopScanInternal(BluetoothLeScannerImplLollipop.java:100)
   at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerCompat.stopScan(BluetoothLeScannerCompat.java:232)
```

**Comment by philips77** [comment]
Hello,
This is kind of expected. Newer Android versions require the Bluetooth to be ON for some operations. You may wrap it in try-catch or check the state before calling the `stopScan()` method.
