### ISSUE TITLE
BT le scanner not available.

### ISSUE THREAD

**Issue by ve00ym803** [NordicSemiconductor/Android-Scanner-Compat-Library#147]
On calling this:
```java
mBluetoothLeScanner = BluetoothLeScannerCompat.getScanner();
```
I am getting below error. My Android version is 11 but still it's going to this method `BluetoothLeScannerImplLollipop()`. As per the code, it should go to this method as: `BluetoothLeScannerImplOreo()`. 
            
Not sure how this is happening. I got this error via crashlytics today.
```
Fatal Exception: java.lang.IllegalStateException: BT le scanner not available
       at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerImplLollipop.startScanInternal(BluetoothLeScannerImplLollipop.java:60)
       at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerCompat.startScan(BluetoothLeScannerCompat.java:173)
       at ymsli.com.yanswerback.services.BLEService.scanForDevices(BLEService.java:421)
       at ymsli.com.yanswerback.services.BLEService$PeriodicReconnectionTimer$1.lambda$run$0(BLEService.java:962)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

**Comment by philips77** [comment]
The error is thrown from here:
https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library/blob/9e4094195ae2ea44617eca851ad208dda8143ec6/scanner/src/main/java/no/nordicsemi/android/support/v18/scanner/BluetoothLeScannerImplLollipop.java#L58-L60
Make sure the Bluetooth is available and ON before starting scanning, or catch the error and report to the user.

`BluetoothLeScannerImplOreo` extends `BluetoothLeScannerImplMarshmallow`, which extends `BluetoothLeScannerImplLollipop` and they share the same implementation of `startScanInternal(...)` method, so that's not an issue.
