### ISSUE TITLE
How do I implement a fake BLE device when I want to run my BLE scanner on an AVD?

### ISSUE THREAD

**Issue by nari4169** [NordicSemiconductor/Android-Scanner-Compat-Library#149]
First of all, I would like to express my gratitude for your library.
I am implementing an app using your library. It works fine on the actual device. However, when I try to debug the app using AVD, the bluetooth device does not work on AVD, so I want to deceive the callback of startScan as if there is a fake bluetooth device. Is my code wrong?

I would really appreciate it if you could give me a hint.
The following is my code, and the error message is displayed as shown below.
This code was written by referring to the results searched through AI.

It seems like it's not working because createMockScanRecord() is not being created and null is being returned. I can't create scanrecord, can you tell me another alternative?

Thank you again.

-----------------------------------------------------------------------------------------------
source code :
```kotlin
// Mock BluetoothDevice 생성
    fun createMockBluetoothDevice(address: String, name: String): android.bluetooth.BluetoothDevice {
        val constructor = android.bluetooth.BluetoothDevice::class.java.getDeclaredConstructor(String::class.java)
        constructor.isAccessible = true
        val device = constructor.newInstance(address)

        return device
    }

    // Mock ScanRecord 생성
    fun createMockScanRecord(): ScanRecord? {
        return try {
            val constructor: Constructor<ScanRecord> = ScanRecord::class.java.getDeclaredConstructor(
                ByteArray::class.java, // 광고 데이터
                ByteArray::class.java, // 스캔 응답 데이터
                List::class.java, // 서비스 UUIDs
                Int::class.javaPrimitiveType, // 광고 플래그
                Int::class.javaPrimitiveType, // TxPowerLevel
                String::class.java, // Device Name
                Int::class.javaPrimitiveType // Manufacturer Specific Data
            )
            constructor.isAccessible = true
            constructor.newInstance(
                byteArrayOf(0x02, 0x01, 0x06), // 광고 데이터
                byteArrayOf(0x09, 0x09, 0x4D, 0x6F, 0x63, 0x6B, 0x20, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65), // 스캔 응답 데이터
                listOf(""), // 서비스 UUIDs
                -1, // 광고 플래그
                0, // TxPowerLevel
                "Mock Device", // Device Name
                0 // Manufacturer Specific Data
            )
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }

    // Mock ScanResult 생성
    fun createMockScanResult(): ScanResult {
        val mockDevice = createMockBluetoothDevice("00:11:22:33:44:55", "Mock Device")
        val mockScanRecord = createMockScanRecord()
        loge("createMockScanResult mockScanRecord: $mockScanRecord")
        return ScanResult(mockDevice, mockScanRecord, 0, System.nanoTime())
    }

    val mockScanResult = createMockScanResult()

    val debugScanCallback = object : ScanCallback() {
        override fun onScanResult(callbackType: Int, result: ScanResult) {
            super.onScanResult(callbackType, mockScanResult)
            // 결과 처리
            viewModel.setScanResults(listOf(mockScanResult))
            loge("debugScanCallback result: $result")
        }

        override fun onBatchScanResults(results: List<ScanResult>) {
            super.onBatchScanResults(listOf(mockScanResult))
            // 결과 처리
            loge("debugScanCallback results: $results")
            viewModel.setScanResults(results)
        }

        override fun onScanFailed(errorCode: Int) {
            super.onScanFailed(errorCode)
            // 오류 처리
            loge("debugScanCallback errorCode: $errorCode")
        }
    }

    private fun scanDevice() {
        val settings: ScanSettings = ScanSettings.Builder()
            .setLegacy(false)
            .setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY)
            .setReportDelay(1500)
            .setUseHardwareBatchingIfSupported(false)
            .build()

        val scanFilter = ScanFilter.Builder()
            .setServiceUuid(ParcelUuid.fromString(Constant.RX_SERVICE_UUID_TEXT))
            .build()

        if (BuildConfig.DEBUG) {
            loge("1 buildConfig. ${BuildConfig.DEBUG} -----------------------------------------")
            scanner.startScan(listOf(scanFilter), settings, debugScanCallback)
        } else {
            loge("2 buildConfig. ${BuildConfig.DEBUG} -----------------------------------------")
            scanner.startScan(listOf(scanFilter), settings, scanCallback)
        }
    }
```
-----------------------------------------------------------------------------------------------
Error cat log
```
07:43:20.010  W  Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (unsupported, reflection, allowed)
07:43:20.245  W  Accessing hidden method Landroid/bluetooth/BluetoothDevice;-><init>(Ljava/lang/String;)V (unsupported, reflection, allowed)
07:43:20.251  W  java.lang.NoSuchMethodException: no.nordicsemi.android.support.v18.scanner.ScanRecord.<init> [class [B, class [B, interface java.util.List, int, int, class java.lang.String, int]
07:43:20.255  W  	at java.lang.Class.getConstructor0(Class.java:2363)
07:43:20.255  W  	at java.lang.Class.getDeclaredConstructor(Class.java:2201)
07:43:20.255  W  	at ted.jangsu10.sleep.ui.feature.onboarding.scan.OnBoardingScanFragment.createMockScanRecord(OnBoardingScanFragment.kt:52)
07:43:20.255  W  	at ted.jangsu10.sleep.ui.feature.onboarding.scan.OnBoardingScanFragment.createMockScanResult(OnBoardingScanFragment.kt:80)
07:43:20.255  W  	at ted.jangsu10.sleep.ui.feature.onboarding.scan.OnBoardingScanFragment.<init>(OnBoardingScanFragment.kt:85)
07:43:20.255  W  	at java.lang.Class.newInstance(Native Method)
07:43:20.255  W  	at ted.jangsu10.sleep.ui.base.template.FragmentTemplate.newInstance(FragmentTemplate.kt:56)
07:43:20.255  W  	at ted.jangsu10.sleep.ui.feature.onboarding.OnBoardingActivity.setupViewPager(OnBoardingActivity.kt:73)
07:43:20.255  W  	at ted.jangsu10.sleep.ui.feature.onboarding.OnBoardingActivity.onCreate(OnBoardingActivity.kt:54)
07:43:20.255  W  	at android.app.Activity.performCreate(Activity.java:8057)
07:43:20.255  W  	at android.app.Activity.performCreate(Activity.java:8037)
07:43:20.255  W  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
07:43:20.255  W  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
07:43:20.255  W  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
07:43:20.255  W  	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
07:43:20.255  W  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07:43:20.255  W  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07:43:20.255  W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
07:43:20.255  W  	at android.os.Handler.dispatchMessage(Handler.java:106)
07:43:20.255  W  	at android.os.Looper.loopOnce(Looper.java:201)
07:43:20.256  W  	at android.os.Looper.loop(Looper.java:288)
07:43:20.256  W  	at android.app.ActivityThread.main(ActivityThread.java:7870)
07:43:20.256  W  	at java.lang.reflect.Method.invoke(Native Method)
07:43:20.256  W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07:43:20.256  W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by philips77** [comment]
Hi,
We're working on a new library [Kotlin BLE Library - version/2.0](https://github.com/NordicSemiconductor/Kotlin-BLE-Library/tree/version/2.0) which we want to support mock scanning and mock advertising. If your app is targeting Android 5 or newer, please consider it. Version 2 is in early alpha stage and not published yet to Maven, but more and more features will be added.

If you'd like to use this library, consider cloning the repo and adding it to your project as a module like that:
https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/9fa7dea61a07d6d939a293761eead84497df07be/settings.gradle#L6-L8
Then you may modify the source code and tailor it for your needs.
