### ISSUE TITLE
Scanner behavior with flight mode changes

### ISSUE THREAD

**Issue by schlachtzeuger** [NordicSemiconductor/Android-Scanner-Compat-Library#87]
Hi there,

I'm using the current 1.4.3 version of the lib and have some issues: When I do scan and switch on the flight mode in the settings, scanning can not be stopped because the scanner is not available:

`
    java.lang.IllegalStateException: BT le scanner not available
        at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerImplOreo.stopScanInternal(BluetoothLeScannerImplOreo.java:121)
        at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerCompat.stopScan(BluetoothLeScannerCompat.java:297)
`
After Bluetooth was enabled afterwards or the flight mode was deactivated, I cannot start scanning again because it thinks it never stopped scanning:

`
    java.lang.IllegalArgumentException: scanner already started with given callback
        at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerImplLollipop.startScanInternal(BluetoothLeScannerImplLollipop.java:70)
        at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerCompat.startScan(BluetoothLeScannerCompat.java:159)
`

For testing, I have a Samsung S8 running Android 9.

**Comment by schlachtzeuger** [comment]
Never mind, it was a mistake by myself because I'm watching the Bluetooth state and was trying to stop the scan on STATE_OFF instead of STATE_TURNING_OFF.
